<?php

namespace App\Models;

use App\Models\Concerns\HasUuid;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;

class Company extends Model
{
    use HasFactory, HasUuid;

    protected $fillable = [
        'uuid',
        'name',
        'registration_no',
        'address',
    ];

    // Note: uuid is auto-generated by HasUuid trait, but can be manually set in seeders

    /**
     * Get all departments for this company
     */
    public function departments(): HasMany
    {
        return $this->hasMany(Department::class);
    }

    /**
     * Get all employees for this company
     */
    public function employees(): HasMany
    {
        return $this->hasMany(Employee::class);
    }
}
