<?php

namespace App\Models;

use App\Models\Concerns\HasUuid;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Database\Eloquent\Relations\HasMany;

class Employee extends CompanyScopedModel
{
    use HasUuid;

    protected $fillable = [
        'uuid',
        'user_id',
        'company_id',
        'department_id',
        'position_id',
        'employee_no',
        'employment_type',
        'hire_date',
        'termination_date',
        'status',
    ];

    protected $casts = [
        'hire_date' => 'date',
        'termination_date' => 'date',
    ];

    // Note: uuid is auto-generated by HasUuid trait, but can be manually set in seeders

    /**
     * Get the user that owns the employee
     */
    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }

    /**
     * Get the company that the employee belongs to
     */
    public function company(): BelongsTo
    {
        return $this->belongsTo(Company::class);
    }

    /**
     * Get the department that the employee belongs to
     */
    public function department(): BelongsTo
    {
        return $this->belongsTo(Department::class);
    }

    /**
     * Get the position that the employee has
     */
    public function position(): BelongsTo
    {
        return $this->belongsTo(Position::class);
    }

    /**
     * Get all salaries for this employee
     */
    public function salaries(): HasMany
    {
        return $this->hasMany(Salary::class);
    }

    /**
     * Get all employee deductions for this employee
     */
    public function employeeDeductions(): HasMany
    {
        return $this->hasMany(EmployeeDeduction::class);
    }

    /**
     * Get all employee allowances for this employee
     */
    public function employeeAllowances(): HasMany
    {
        return $this->hasMany(EmployeeAllowance::class);
    }

    /**
     * Get all attendance records for this employee
     */
    public function attendances(): HasMany
    {
        return $this->hasMany(Attendance::class);
    }

    /**
     * Get all leave balances for this employee
     */
    public function leaves(): HasMany
    {
        return $this->hasMany(Leave::class);
    }

    /**
     * Get all leave requests for this employee
     */
    public function leaveRequests(): HasMany
    {
        return $this->hasMany(LeaveRequest::class);
    }

    /**
     * Get all loans for this employee
     */
    public function loans(): HasMany
    {
        return $this->hasMany(Loan::class);
    }

    /**
     * Get all contributions assigned to this employee
     */
    public function employeeContributions(): HasMany
    {
        return $this->hasMany(EmployeeContribution::class);
    }

    /**
     * Get contributions through pivot table
     */
    public function contributions(): BelongsToMany
    {
        return $this->belongsToMany(Contribution::class, 'employee_contributions')
            ->withTimestamps();
    }
}
