<?php

namespace App\Models;

use App\Models\Concerns\HasUuid;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class Employee extends Model
{
    use HasUuid;

    protected $fillable = [
        'uuid',
        'user_id',
        'company_id',
        'department_id',
        'position_id',
        'employee_no',
        'employment_type',
        'hire_date',
        'termination_date',
        'status',
    ];

    protected $casts = [
        'hire_date' => 'date',
        'termination_date' => 'date',
    ];

    // Note: uuid is auto-generated by HasUuid trait, but can be manually set in seeders

    /**
     * Get the user that owns the employee
     */
    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }

    /**
     * Get the company that the employee belongs to
     */
    public function company(): BelongsTo
    {
        return $this->belongsTo(Company::class);
    }

    /**
     * Get the department that the employee belongs to
     */
    public function department(): BelongsTo
    {
        return $this->belongsTo(Department::class);
    }

    /**
     * Get the position that the employee has
     */
    public function position(): BelongsTo
    {
        return $this->belongsTo(Position::class);
    }
}
