<?php

namespace App\Models;

use App\Models\Concerns\HasUuid;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;

class Position extends Model
{
    use HasFactory, HasUuid;

    protected $fillable = [
        'uuid',
        'department_id',
        'title',
    ];

    // Note: uuid is auto-generated by HasUuid trait, but can be manually set in seeders

    /**
     * Get the department that owns this position
     */
    public function department(): BelongsTo
    {
        return $this->belongsTo(Department::class);
    }

    /**
     * Get all employees with this position
     */
    public function employees(): HasMany
    {
        return $this->hasMany(Employee::class);
    }
}
